name: CI for Kernal Kings

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch
  workflow_dispatch:  # Allows manual triggering via GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
