name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx

      - name: Build and run Docker Compose
        run: |
          docker-compose -f .github/workflows/docker-compose.yml up --build -d  # Build and run Docker Compose
          docker ps  # List running containers for verification

      - name: Deploy to Heroku (or any other deployment platform)
        run: |
          heroku container:login
          heroku container:push web --app your-heroku-app-name
          heroku container:release web --app your-heroku-app-name

