name: Manual workflow for Kernal Kings

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:  # Allows triggering manually via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository

      # Step 2: Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use Node.js version 14

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install  # Install all dependencies defined in package.json

      # Step 4: Check Node version
      - name: Check Node version
        run: node --version

      # Step 5: Run tests (currently running a basic test for demonstration)
      - name: Run tests
        run: npm test
